import Head from "next/head";

export default function Analytics() {
  return (
    <>
      <Head>
        <title>Squinterview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>{"What's happening"}</h1>
        <div style={{ flex: 1 }}>Hello world!</div>
      </main>
    </>
  );
}
