import TriangleCanvas from "@/components/TriangleCanvas";
import TriangleForm from "@/components/TriangleForm";
import TriangleList from "@/components/TriangleList";
import { LOCAL_STORAGE_KEY } from "@/constants";
import { TriangleContext } from "@/contexts/triangleContext";
import useLocalStorage from "@/hooks/useLocalStorage";
import { PointDict } from "@/types";
import { Container, Row, Col } from "@nextui-org/react";
import Head from "next/head";
import React, { createContext, useEffect, useState } from "react";

export const ClientStatus = createContext(false);

export default function Home() {
  const [triangles, setTriangles] = useLocalStorage<PointDict[]>(
    LOCAL_STORAGE_KEY,
    []
  );
  const [clientLoaded, setClientLoaded] = useState(false);

  useEffect(() => {
    setClientLoaded(true);
  }, []);

  return (
    <>
      <Head>
        <title>Squinterview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <ClientStatus.Provider value={clientLoaded}>
          <TriangleContext.Provider value={{ triangles, setTriangles }}>
            <Container gap={1}>
              <Row gap={2}>
                <Col>
                  <TriangleForm />
                </Col>
                <Col>
                  <TriangleList />
                </Col>
                <Col>
                  <TriangleCanvas />
                </Col>
              </Row>
            </Container>
          </TriangleContext.Provider>
        </ClientStatus.Provider>
      </main>
    </>
  );
}
