import TriangleCanvas from "@/components/TriangleCanvas";
import TriangleForm from "@/components/TriangleForm";
import useLocalStorage from "@/hooks/useLocalStorage";
import { PointDict } from "@/types";
import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";

export default function Home() {
  const [triangles, setTriangles] = useLocalStorage<PointDict[]>(
    "triangleData",
    []
  );
  const [clientLoaded, setClientLoaded] = useState(false);

  useEffect(() => {
    setClientLoaded(true);
  }, []);

  const deleteTriangle = (index: number) => {
    const newTriangles = triangles.filter((_, idx) => idx !== index);
    setTriangles(newTriangles);
  };

  const renderTriangleList = () => {
    if (!clientLoaded) return null;
    return triangles.map((triangle: PointDict, index: number) => {
      return (
        <div key={JSON.stringify(triangle)}>
          {Object.keys(triangle).map((point) => {
            return (
              <span
                key={point}
              >{`(${triangle[point].X}, ${triangle[point].Y})`}</span>
            );
          })}
          <button onClick={() => deleteTriangle(index)}>Delete</button>
        </div>
      );
    });
  };

  return (
    <>
      <Head>
        <title>Squinterview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flex: 1,
            flexDirection: "row",
            justifyContent: "space-evenly",
          }}
        >
          <TriangleForm setTriangles={setTriangles} triangles={triangles} />
          <div className="existingTriangles" style={{ flex: 0.5 }}>
            {renderTriangleList()}
          </div>
          <TriangleCanvas triangles={triangles} />
        </div>
      </main>
    </>
  );
}
